[package]
name = "persway"
version = "0.1.0"
authors = ["John Axel Eriksson <john@insane.se>"]
edition = "2018"

[dependencies]
failure = "0.1.5"
exitfailure = "0.5.1"
i3ipc = "0.10.1"
signal-hook = "0.1.8"